structure(list(tab_dim_id = c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L), level_value = c("P3_P5", "P3", "P31_S14_D", 
"P31_S14_N", "P311_S14", "P31K_S14", "P31_S15", "P3_S13", "P31_S13", 
"P32_S13", "P5", "P51G", "P51G_N11KG", "P51G_N111G", "P51G_N112G", 
"P51G_N11MG", "P51G_N1131G", "P51G_N11OG_N1132G", "P51G_N115G", 
"P51G_N117G", "P52", "P53", "B11", "P6", "P61", "P62", "P7", 
"P71", "P72", "B1GQ"), level_text = c("Domaèa potrošnja", "..Konèna potrošnja", 
"....Konèna potrošnja gospodinjstev (nacionalni koncept)", "......od tega: konèna potrošnja gospodinjstev (domaèi koncept)", 
"........Trajni proizvodi", "........Drugi proizvodi", "....Konèna potrošnja NPISG", 
"....Konèna potrošnja države", "......Individualna konèna potrošnja države", 
"......Kolektivna konèna potrošnja države", "..Bruto investicije", 
"....Bruto investicije v osnovna sredstva", "......Zgradbe in objekti", 
"........Stanovanja", "........Druge zgradbe in objekti", "......Oprema in stroji", 
"........Transportna oprema", "........Druga oprema in stroji", 
"......Osnovna èreda in veèletni nasadi", "......Proizvodi intelektualne lastnine", 
"....Spremembe zalog", "....Vrednostni predmeti", "Saldo menjave s tujino", 
"..Izvoz blaga in storitev", "....Izvoz blaga", "....Izvoz storitev", 
"..Minus: uvoz blaga in storitev", "....Uvoz blaga", "....Uvoz storitev", 
"Bruto domaèi proizvod")), class = "data.frame", row.names = c(NA, 
-30L))
