test_that("check API response is appropriate and the parsing works", {
  rsp <- get_structAPI_response()
  expect_true(is.character(rsp))
  expect_gte(nchar(rsp), 2000000)
  out.tree <- parse_structAPI_response(rsp)
  expect_true(is.environment(out.tree))
  out <- parse_structAPI_response(rsp, output = "lol")
  expect_true(is.list(out))
  out <- parse_structAPI_response(rsp, output = "df")
  expect_true(is.data.frame(out))
  out.na <- parse_structAPI_response(rsp, output = "bb")
  expect_true(is.na(out.na))
  df <- get_full_structure(out.tree)
  expect_true(is.data.frame(df))
  expect_equal(ncol(df), 8)
  matrix <- get_matrix_hierarchy(df)
  expect_true(is.data.frame(matrix))
  expect_equal(ncol(matrix), 8)
  expect_lte(nrow(matrix), nrow(df))
  fields <- get_field_hierarchy(df)
  expect_true(is.data.frame(fields))
  expect_equal(ncol(fields), 5)
  expect_equal(nrow(matrix)+nrow(fields), nrow(df))
  m.tree <- get_tree(matrix)
  expect_true(is.environment(m.tree))
})


